// ============================================================
// EXTENDED US STOCK UNIVERSE — S&P 500 + Russell 1000
// Compact format: [ticker, name, sector, price, marketCapB, pe]
// marketCapB = market cap in billions USD
// pe = P/E ratio (0 = N/A)
// ============================================================

type CompactStock = [string, string, string];
type CompactStock5 = [string, string, string];

export const SP500_COMPACT: CompactStock[] = [
    // ── TECHNOLOGY ──────────────────────────────────────────────
    ['AAPL', 'Apple Inc.', 'Technology'],
    ['MSFT', 'Microsoft Corp.', 'Technology'],
    ['NVDA', 'NVIDIA Corp.', 'Technology'],
    ['GOOGL', 'Alphabet Inc.', 'Technology'],
    ['META', 'Meta Platforms', 'Technology'],
    ['AMZN', 'Amazon.com Inc.', 'Technology'],
    ['AMD', 'Advanced Micro Devices', 'Technology'],
    ['INTC', 'Intel Corp.', 'Technology'],
    ['CRM', 'Salesforce Inc.', 'Technology'],
    ['AVGO', 'Broadcom Inc.', 'Technology'],
    ['ORCL', 'Oracle Corp.', 'Technology'],
    ['CSCO', 'Cisco Systems', 'Technology'],
    ['QCOM', 'Qualcomm Inc.', 'Technology'],
    ['TXN', 'Texas Instruments', 'Technology'],
    ['NOW', 'ServiceNow Inc.', 'Technology'],
    ['ADBE', 'Adobe Inc.', 'Technology'],
    ['AMAT', 'Applied Materials', 'Technology'],
    ['MU', 'Micron Technology', 'Technology'],
    ['KLAC', 'KLA Corp.', 'Technology'],
    ['LRCX', 'Lam Research', 'Technology'],
    ['MRVL', 'Marvell Technology', 'Technology'],
    ['ADI', 'Analog Devices', 'Technology'],
    ['NXPI', 'NXP Semiconductors', 'Technology'],
    ['MCHP', 'Microchip Technology', 'Technology'],
    ['PANW', 'Palo Alto Networks', 'Technology'],
    ['CRWD', 'CrowdStrike Holdings', 'Technology'],
    ['FTNT', 'Fortinet Inc.', 'Technology'],
    ['SNPS', 'Synopsys Inc.', 'Technology'],
    ['CDNS', 'Cadence Design', 'Technology'],
    ['ANSS', 'Ansys Inc.', 'Technology'],
    ['EPAM', 'EPAM Systems', 'Technology'],
    ['FFIV', 'F5 Inc.', 'Technology'],
    ['GLW', 'Corning Inc.', 'Technology'],
    ['HPQ', 'HP Inc.', 'Technology'],
    ['HPE', 'Hewlett Packard Enterprise', 'Technology'],
    ['IBM', 'IBM Corp.', 'Technology'],
    ['KEYS', 'Keysight Technologies', 'Technology'],
    ['NTAP', 'NetApp Inc.', 'Technology'],
    ['PAYC', 'Paycom Software', 'Technology'],
    ['AKAM', 'Akamai Technologies', 'Technology'],
    ['CDW', 'CDW Corp.', 'Technology'],
    ['CTSH', 'Cognizant Technology', 'Technology'],
    ['WDC', 'Western Digital', 'Technology'],
    ['STX', 'Seagate Technology', 'Technology'],
    ['ZBRA', 'Zebra Technologies', 'Technology'],
    ['TDY', 'Teledyne Technologies', 'Technology'],
    ['NDSN', 'Nordson Corp.', 'Technology'],
    ['GEN', 'Gen Digital', 'Technology'],
    ['JNPR', 'Juniper Networks', 'Technology'],
    ['SWKS', 'Skyworks Solutions', 'Technology'],

    // ── FINANCIALS ──────────────────────────────────────────────
    ['JPM', 'JPMorgan Chase', 'Financials'],
    ['BAC', 'Bank of America', 'Financials'],
    ['WFC', 'Wells Fargo', 'Financials'],
    ['GS', 'Goldman Sachs', 'Financials'],
    ['MS', 'Morgan Stanley', 'Financials'],
    ['V', 'Visa Inc.', 'Financials'],
    ['MA', 'Mastercard Inc.', 'Financials'],
    ['AXP', 'American Express', 'Financials'],
    ['BLK', 'BlackRock Inc.', 'Financials'],
    ['SCHW', 'Charles Schwab', 'Financials'],
    ['C', 'Citigroup Inc.', 'Financials'],
    ['USB', 'US Bancorp', 'Financials'],
    ['PNC', 'PNC Financial', 'Financials'],
    ['TFC', 'Truist Financial', 'Financials'],
    ['BK', 'BNY Mellon', 'Financials'],
    ['COF', 'Capital One', 'Financials'],
    ['DFS', 'Discover Financial', 'Financials'],
    ['SYF', 'Synchrony Financial', 'Financials'],
    ['MTB', 'M&T Bank', 'Financials'],
    ['FITB', 'Fifth Third Bancorp', 'Financials'],
    ['KEY', 'KeyCorp', 'Financials'],
    ['RF', 'Regions Financial', 'Financials'],
    ['HBAN', 'Huntington Bancshares', 'Financials'],
    ['CFG', 'Citizens Financial', 'Financials'],
    ['SIVB', 'SVB Financial', 'Financials'],
    ['ZION', 'Zions Bancorporation', 'Financials'],
    ['CBOE', 'Cboe Global Markets', 'Financials'],
    ['CME', 'CME Group', 'Financials'],
    ['ICE', 'Intercontinental Exch.', 'Financials'],
    ['NDAQ', 'Nasdaq Inc.', 'Financials'],
    ['SPGI', 'S&P Global', 'Financials'],
    ['MCO', 'Moody\'s Corp.', 'Financials'],
    ['AFL', 'Aflac Inc.', 'Financials'],
    ['MET', 'MetLife Inc.', 'Financials'],
    ['PRU', 'Prudential Financial', 'Financials'],
    ['AIG', 'American Intl Group', 'Financials'],
    ['CINF', 'Cincinnati Financial', 'Financials'],
    ['CB', 'Chubb Ltd.', 'Financials'],
    ['ALL', 'Allstate Corp.', 'Financials'],
    ['HIG', 'Hartford Financial', 'Financials'],
    ['RE', 'Everest Group', 'Financials'],
    ['WRB', 'W.R. Berkley', 'Financials'],
    ['GL', 'Globe Life', 'Financials'],
    ['BRK-B', 'Berkshire Hathaway B', 'Financials'],

    // ── HEALTHCARE ──────────────────────────────────────────────
    ['JNJ', 'Johnson & Johnson', 'Healthcare'],
    ['UNH', 'UnitedHealth Group', 'Healthcare'],
    ['ABBV', 'AbbVie Inc.', 'Healthcare'],
    ['LLY', 'Eli Lilly & Co.', 'Healthcare'],
    ['PFE', 'Pfizer Inc.', 'Healthcare'],
    ['MRK', 'Merck & Co.', 'Healthcare'],
    ['TMO', 'Thermo Fisher', 'Healthcare'],
    ['DHR', 'Danaher Corp.', 'Healthcare'],
    ['ABT', 'Abbott Laboratories', 'Healthcare'],
    ['BMY', 'Bristol-Myers Squibb', 'Healthcare'],
    ['AMGN', 'Amgen Inc.', 'Healthcare'],
    ['GILD', 'Gilead Sciences', 'Healthcare'],
    ['ISRG', 'Intuitive Surgical', 'Healthcare'],
    ['SYK', 'Stryker Corp.', 'Healthcare'],
    ['BSX', 'Boston Scientific', 'Healthcare'],
    ['MDT', 'Medtronic PLC', 'Healthcare'],
    ['EW', 'Edwards Lifesciences', 'Healthcare'],
    ['BDX', 'Becton Dickinson', 'Healthcare'],
    ['ZBH', 'Zimmer Biomet', 'Healthcare'],
    ['HOLX', 'Hologic Inc.', 'Healthcare'],
    ['VAR', 'Varian Medical', 'Healthcare'],
    ['HUM', 'Humana Inc.', 'Healthcare'],
    ['CI', 'Cigna Group', 'Healthcare'],
    ['ELV', 'Elevance Health', 'Healthcare'],
    ['CVS', 'CVS Health', 'Healthcare'],
    ['MCK', 'McKesson Corp.', 'Healthcare'],
    ['ABC', 'AmerisourceBergen', 'Healthcare'],
    ['CAH', 'Cardinal Health', 'Healthcare'],
    ['CNC', 'Centene Corp.', 'Healthcare'],
    ['MOH', 'Molina Healthcare', 'Healthcare'],
    ['DGX', 'Quest Diagnostics', 'Healthcare'],
    ['LH', 'LabCorp', 'Healthcare'],
    ['IQVIA', 'IQVIA Holdings', 'Healthcare'],
    ['IQV', 'IQVIA Holdings', 'Healthcare'],
    ['VRTX', 'Vertex Pharmaceuticals', 'Healthcare'],
    ['REGN', 'Regeneron Pharmaceuticals', 'Healthcare'],
    ['BIIB', 'Biogen Inc.', 'Healthcare'],
    ['MRNA', 'Moderna Inc.', 'Healthcare'],
    ['ILMN', 'Illumina Inc.', 'Healthcare'],

    // ── CONSUMER DISCRETIONARY ──────────────────────────────────
    ['TSLA', 'Tesla Inc.', 'Consumer'],
    ['AMZN2', 'Amazon Consumer', 'Consumer'],
    ['HD', 'Home Depot', 'Consumer'],
    ['MCD', 'McDonald\'s Corp.', 'Consumer'],
    ['NKE', 'Nike Inc.', 'Consumer'],
    ['SBUX', 'Starbucks Corp.', 'Consumer'],
    ['TGT', 'Target Corp.', 'Consumer'],
    ['COST', 'Costco Wholesale', 'Consumer'],
    ['LOW', 'Lowe\'s Companies', 'Consumer'],
    ['BKNG', 'Booking Holdings', 'Consumer'],
    ['MAR', 'Marriott International', 'Consumer'],
    ['HLT', 'Hilton Worldwide', 'Consumer'],
    ['YUM', 'Yum! Brands', 'Consumer'],
    ['DPZ', 'Domino\'s Pizza', 'Consumer'],
    ['CMG', 'Chipotle Mexican Grill', 'Consumer'],
    ['DKNG', 'DraftKings Inc.', 'Consumer'],
    ['MGM', 'MGM Resorts', 'Consumer'],
    ['WYNN', 'Wynn Resorts', 'Consumer'],
    ['LVS', 'Las Vegas Sands', 'Consumer'],
    ['CZR', 'Caesars Entertainment', 'Consumer'],
    ['NFLX', 'Netflix Inc.', 'Consumer'],
    ['DIS', 'Walt Disney Co.', 'Consumer'],
    ['PARA', 'Paramount Global', 'Consumer'],
    ['WBD', 'Warner Bros. Discovery', 'Consumer'],
    ['FOXA', 'Fox Corp.', 'Consumer'],
    ['NWS', 'News Corp.', 'Consumer'],
    ['RL', 'Ralph Lauren', 'Consumer'],
    ['PVH', 'PVH Corp.', 'Consumer'],
    ['HAS', 'Hasbro Inc.', 'Consumer'],
    ['MAT', 'Mattel Inc.', 'Consumer'],
    ['EBAY', 'eBay Inc.', 'Consumer'],
    ['ETSY', 'Etsy Inc.', 'Consumer'],
    ['ABNB', 'Airbnb Inc.', 'Consumer'],
    ['UBER', 'Uber Technologies', 'Consumer'],
    ['LYFT', 'Lyft Inc.', 'Consumer'],
    ['F', 'Ford Motor Co.', 'Consumer'],
    ['GM', 'General Motors', 'Consumer'],
    ['TM', 'Toyota Motor ADR', 'Consumer'],
    ['HOG', 'Harley-Davidson', 'Consumer'],

    // ── CONSUMER STAPLES ────────────────────────────────────────
    ['WMT', 'Walmart Inc.', 'Consumer'],
    ['PG', 'Procter & Gamble', 'Consumer'],
    ['KO', 'Coca-Cola Co.', 'Consumer'],
    ['PEP', 'PepsiCo Inc.', 'Consumer'],
    ['PM', 'Philip Morris Intl.', 'Consumer'],
    ['MO', 'Altria Group', 'Consumer'],
    ['KHC', 'Kraft Heinz Co.', 'Consumer'],
    ['GIS', 'General Mills', 'Consumer'],
    ['CPB', 'Campbell Soup', 'Consumer'],
    ['K', 'Kellanova', 'Consumer'],
    ['HSY', 'Hershey Co.', 'Consumer'],
    ['CAG', 'Conagra Brands', 'Consumer'],
    ['SJM', 'J.M. Smucker', 'Consumer'],
    ['HRL', 'Hormel Foods', 'Consumer'],
    ['TSN', 'Tyson Foods', 'Consumer'],
    ['MKC', 'McCormick & Co.', 'Consumer'],
    ['CLX', 'Clorox Co.', 'Consumer'],
    ['CHD', 'Church & Dwight', 'Consumer'],
    ['EL', 'Estée Lauder', 'Consumer'],
    ['CL', 'Colgate-Palmolive', 'Consumer'],
    ['KMB', 'Kimberly-Clark', 'Consumer'],
    ['AVP', 'Avon Products', 'Consumer'],
    ['COTY', 'Coty Inc.', 'Consumer'],
    ['CVS2', 'CVS Pharmacy', 'Consumer'],
    ['KR', 'Kroger Co.', 'Consumer'],
    ['SFM', 'Sprouts Farmers Market', 'Consumer'],
    ['ACI', 'Albertsons Companies', 'Consumer'],

    // ── ENERGY ──────────────────────────────────────────────────
    ['XOM', 'ExxonMobil Corp.', 'Energy'],
    ['CVX', 'Chevron Corp.', 'Energy'],
    ['COP', 'ConocoPhillips', 'Energy'],
    ['EOG', 'EOG Resources', 'Energy'],
    ['SLB', 'Schlumberger Ltd.', 'Energy'],
    ['PXD', 'Pioneer Natural Resources', 'Energy'],
    ['PSX', 'Phillips 66', 'Energy'],
    ['VLO', 'Valero Energy', 'Energy'],
    ['MPC', 'Marathon Petroleum', 'Energy'],
    ['OXY', 'Occidental Petroleum', 'Energy'],
    ['HES', 'Hess Corp.', 'Energy'],
    ['DVN', 'Devon Energy', 'Energy'],
    ['FANG', 'Diamondback Energy', 'Energy'],
    ['FA', 'First Advantage', 'Energy'],
    ['APA', 'APA Corp.', 'Energy'],
    ['MRO', 'Marathon Oil Corp.', 'Energy'],
    ['HAL', 'Halliburton Co.', 'Energy'],
    ['BKR', 'Baker Hughes Co.', 'Energy'],
    ['NOV', 'NOV Inc.', 'Energy'],
    ['CTRA', 'Coterra Energy', 'Energy'],
    ['RRC', 'Range Resources', 'Energy'],
    ['EQT', 'EQT Corp.', 'Energy'],
    ['AR', 'Antero Resources', 'Energy'],
    ['KMI', 'Kinder Morgan', 'Energy'],
    ['WMB', 'Williams Companies', 'Energy'],
    ['OKE', 'ONEOK Inc.', 'Energy'],
    ['ET', 'Energy Transfer', 'Energy'],
    ['EPD', 'Enterprise Products', 'Energy'],
    ['MMP', 'Magellan Midstream', 'Energy'],

    // ── INDUSTRIALS ─────────────────────────────────────────────
    ['CAT', 'Caterpillar Inc.', 'Industrials'],
    ['HON', 'Honeywell Intl.', 'Industrials'],
    ['GE', 'GE Aerospace', 'Industrials'],
    ['UPS', 'United Parcel Service', 'Industrials'],
    ['BA', 'Boeing Co.', 'Industrials'],
    ['LMT', 'Lockheed Martin', 'Industrials'],
    ['RTX', 'RTX Corp.', 'Industrials'],
    ['NOC', 'Northrop Grumman', 'Industrials'],
    ['GD', 'General Dynamics', 'Industrials'],
    ['DE', 'Deere & Co.', 'Industrials'],
    ['FDX', 'FedEx Corp.', 'Industrials'],
    ['NSC', 'Norfolk Southern', 'Industrials'],
    ['UNP', 'Union Pacific', 'Industrials'],
    ['CSX', 'CSX Corp.', 'Industrials'],
    ['CP', 'Canadian Pacific', 'Industrials'],
    ['LUV', 'Southwest Airlines', 'Industrials'],
    ['DAL', 'Delta Air Lines', 'Industrials'],
    ['UAL', 'United Airlines', 'Industrials'],
    ['AAL', 'American Airlines', 'Industrials'],
    ['ALK', 'Alaska Air Group', 'Industrials'],
    ['JBLU', 'JetBlue Airways', 'Industrials'],
    ['MMM', '3M Co.', 'Industrials'],
    ['EMR', 'Emerson Electric', 'Industrials'],
    ['ROK', 'Rockwell Automation', 'Industrials'],
    ['ETN', 'Eaton Corp.', 'Industrials'],
    ['AME', 'AMETEK Inc.', 'Industrials'],
    ['PH', 'Parker Hannifin', 'Industrials'],
    ['IEX', 'IDEX Corp.', 'Industrials'],
    ['GWW', 'W.W. Grainger', 'Industrials'],
    ['FAST', 'Fastenal Co.', 'Industrials'],
    ['MSA', 'MSA Safety', 'Industrials'],
    ['XYL', 'Xylem Inc.', 'Industrials'],
    ['CARR', 'Carrier Global', 'Industrials'],
    ['OTIS', 'Otis Worldwide', 'Industrials'],
    ['TT', 'Trane Technologies', 'Industrials'],
    ['LII', 'Lennox International', 'Industrials'],
    ['GNRC', 'Generac Holdings', 'Industrials'],
    ['PCAR', 'PACCAR Inc.', 'Industrials'],
    ['CTAS', 'Cintas Corp.', 'Industrials'],
    ['RSG', 'Republic Services', 'Industrials'],
    ['WM', 'Waste Management', 'Industrials'],
    ['CLH', 'Clean Harbors', 'Industrials'],
    ['VRSK', 'Verisk Analytics', 'Industrials'],
    ['HII', 'Huntington Ingalls', 'Industrials'],
    ['TDG', 'TransDigm Group', 'Industrials'],
    ['AXON', 'Axon Enterprise', 'Industrials'],
    ['IR', 'Ingersoll Rand', 'Industrials'],

    // ── UTILITIES ───────────────────────────────────────────────
    ['NEE', 'NextEra Energy', 'Utilities'],
    ['DUK', 'Duke Energy', 'Utilities'],
    ['SO', 'Southern Co.', 'Utilities'],
    ['D', 'Dominion Energy', 'Utilities'],
    ['SRE', 'Sempra Energy', 'Utilities'],
    ['AEP', 'American Electric Power', 'Utilities'],
    ['EXC', 'Exelon Corp.', 'Utilities'],
    ['XEL', 'Xcel Energy', 'Utilities'],
    ['WEC', 'WEC Energy Group', 'Utilities'],
    ['ES', 'Eversource Energy', 'Utilities'],
    ['DTE', 'DTE Energy', 'Utilities'],
    ['PPL', 'PPL Corp.', 'Utilities'],
    ['PEG', 'PSEG', 'Utilities'],
    ['ED', 'Consolidated Edison', 'Utilities'],
    ['EIX', 'Edison International', 'Utilities'],
    ['ETR', 'Entergy Corp.', 'Utilities'],
    ['FE', 'FirstEnergy Corp.', 'Utilities'],
    ['CNP', 'CenterPoint Energy', 'Utilities'],
    ['NI', 'NiSource Inc.', 'Utilities'],
    ['LNT', 'Alliant Energy', 'Utilities'],
    ['AMRC', 'Ameresco Inc.', 'Utilities'],
    ['AES', 'AES Corp.', 'Utilities'],

    // ── REAL ESTATE ─────────────────────────────────────────────
    ['PLD', 'Prologis Inc.', 'Real Estate'],
    ['AMT', 'American Tower', 'Real Estate'],
    ['EQIX', 'Equinix Inc.', 'Real Estate'],
    ['CCI', 'Crown Castle', 'Real Estate'],
    ['SPG', 'Simon Property Group', 'Real Estate'],
    ['O', 'Realty Income', 'Real Estate'],
    ['WELL', 'Welltower Inc.', 'Real Estate'],
    ['VTR', 'Ventas Inc.', 'Real Estate'],
    ['PSA', 'Public Storage', 'Real Estate'],
    ['EXR', 'Extra Space Storage', 'Real Estate'],
    ['AVB', 'AvalonBay Communities', 'Real Estate'],
    ['EQR', 'Equity Residential', 'Real Estate'],
    ['MAA', 'Mid-America Apartment', 'Real Estate'],
    ['UDR', 'UDR Inc.', 'Real Estate'],
    ['CPT', 'Camden Property Trust', 'Real Estate'],
    ['ARE', 'Alexandria Real Estate', 'Real Estate'],
    ['BXP', 'Boston Properties', 'Real Estate'],
    ['KIM', 'Kimco Realty', 'Real Estate'],
    ['REG', 'Regency Centers', 'Real Estate'],
    ['FRT', 'Federal Realty', 'Real Estate'],
    ['VICI', 'VICI Properties', 'Real Estate'],
    ['GLPI', 'Gaming & Leisure Props.', 'Real Estate'],

    // ── MATERIALS ───────────────────────────────────────────────
    ['LIN', 'Linde PLC', 'Materials'],
    ['APD', 'Air Products', 'Materials'],
    ['ECL', 'Ecolab Inc.', 'Materials'],
    ['NEM', 'Newmont Corp.', 'Materials'],
    ['FCX', 'Freeport-McMoRan', 'Materials'],
    ['AA', 'Alcoa Corp.', 'Materials'],
    ['NUE', 'Nucor Corp.', 'Materials'],
    ['STLD', 'Steel Dynamics', 'Materials'],
    ['X', 'US Steel', 'Materials'],
    ['CF', 'CF Industries', 'Materials'],
    ['MOS', 'Mosaic Co.', 'Materials'],
    ['IFF', 'Intl Flavors & Fragrances', 'Materials'],
    ['PPG', 'PPG Industries', 'Materials'],
    ['SHW', 'Sherwin-Williams', 'Materials'],
    ['RPM', 'RPM International', 'Materials'],
    ['BLL', 'Ball Corp.', 'Materials'],
    ['PKG', 'Packaging Corp.', 'Materials'],
    ['IP', 'International Paper', 'Materials'],
    ['SEE', 'Sealed Air Corp.', 'Materials'],
    ['WRK', 'WestRock Co.', 'Materials'],
    ['ATI', 'ATI Inc.', 'Materials'],
    ['CMC', 'Commercial Metals', 'Materials'],
    ['ARNC', 'Arconic Corp.', 'Materials'],
    ['HUN', 'Huntsman Corp.', 'Materials'],
    ['ALB', 'Albemarle Corp.', 'Materials'],
    ['MP', 'MP Materials', 'Materials'],
    ['VALE', 'Vale SA ADR', 'Materials'],
];

export const GLOBAL_COMPACT: CompactStock5[] = [
    // ── UK / LSE ─────────────────────────────────────────────────
    ['SHEL.L', 'Shell PLC', 'Energy'],
    ['HSBA.L', 'HSBC Holdings', 'Financials'],
    ['AZN.L', 'AstraZeneca PLC', 'Healthcare'],
    ['BP.L', 'BP PLC', 'Energy'],
    ['ULVR.L', 'Unilever PLC', 'Consumer'],
    ['RIO.L', 'Rio Tinto Group', 'Materials'],
    ['GSK.L', 'GSK PLC', 'Healthcare'],
    ['LSEG.L', 'London Stock Exchange Group', 'Financials'],
    ['DGE.L', 'Diageo PLC', 'Consumer'],
    ['LLOY.L', 'Lloyds Banking Group', 'Financials'],
    ['NG.L', 'National Grid PLC', 'Utilities'],
    ['REL.L', 'RELX PLC', 'Technology'],
    ['BATS.L', 'British American Tobacco', 'Consumer'],
    ['GLEN.L', 'Glencore PLC', 'Materials'],
    ['RKT.L', 'Reckitt Benckiser', 'Consumer'],
    ['IMB.L', 'Imperial Brands', 'Consumer'],
    ['AHT.L', 'Ashtead Group', 'Industrials'],
    ['CRH.L', 'CRH PLC', 'Materials'],
    ['PSON.L', 'Pearson PLC', 'Technology'],
    ['IHG.L', 'IHG Hotels & Resorts', 'Consumer'],

    // ── JAPAN / TSE ──────────────────────────────────────────────
    ['7203.T', 'Toyota Motor Corp.', 'Consumer'],
    ['9984.T', 'SoftBank Group', 'Technology'],
    ['6758.T', 'Sony Group Corp.', 'Technology'],
    ['7267.T', 'Honda Motor Co.', 'Consumer'],
    ['6501.T', 'Hitachi Ltd.', 'Industrials'],
    ['8306.T', 'Mitsubishi UFJ Financial', 'Financials'],
    ['9432.T', 'NTT Corp.', 'Technology'],
    ['6902.T', 'Denso Corp.', 'Technology'],
    ['4063.T', 'Shin-Etsu Chemical', 'Materials'],
    ['8411.T', 'Mizuho Financial Group', 'Financials'],
    ['8316.T', 'Sumitomo Mitsui Financial', 'Financials'],
    ['9433.T', 'KDDI Corp.', 'Technology'],
    ['3382.T', 'Seven & I Holdings', 'Consumer'],
    ['6367.T', 'Daikin Industries', 'Industrials'],
    ['4502.T', 'Takeda Pharmaceutical', 'Healthcare'],
    ['6201.T', 'Toyoda Automatic Loom', 'Industrials'],
    ['9022.T', 'Central Japan Railway', 'Industrials'],
    ['4661.T', 'Oriental Land (Disney Japan)', 'Consumer'],
    ['6471.T', 'NSK Ltd.', 'Industrials'],
    ['7751.T', 'Canon Inc.', 'Technology'],

    // ── HONG KONG / HKEX ────────────────────────────────────────
    ['0700.HK', 'Tencent Holdings', 'Technology'],
    ['9988.HK', 'Alibaba Group', 'Technology'],
    ['0005.HK', 'HSBC Holdings HK', 'Financials'],
    ['1299.HK', 'AIA Group', 'Financials'],
    ['2318.HK', 'Ping An Insurance', 'Financials'],
    ['3690.HK', 'Meituan', 'Technology'],
    ['0941.HK', 'China Mobile', 'Technology'],
    ['0939.HK', 'China Construction Bank', 'Financials'],
    ['1810.HK', 'Xiaomi Corp.', 'Technology'],
    ['9618.HK', 'JD.com Inc.', 'Technology'],
    ['2388.HK', 'Bank of China (HK)', 'Financials'],
    ['0016.HK', 'Sun Hung Kai Properties', 'Real Estate'],
    ['0002.HK', 'CLP Holdings', 'Utilities'],
    ['6098.HK', 'Country Garden Services', 'Real Estate'],
    ['0669.HK', 'Techtronic Industries', 'Industrials'],
    ['0883.HK', 'CNOOC Ltd.', 'Energy'],
    ['1038.HK', 'CK Infrastructure', 'Utilities'],
    ['2020.HK', 'ANTA Sports Products', 'Consumer'],
    ['1177.HK', 'Sino Biopharmaceutical', 'Healthcare'],
    ['0011.HK', 'Hang Seng Bank', 'Financials'],

    // ── GERMANY / XETRA ──────────────────────────────────────────
    ['SAP.DE', 'SAP SE', 'Technology'],
    ['SIE.DE', 'Siemens AG', 'Industrials'],
    ['ALV.DE', 'Allianz SE', 'Financials'],
    ['BMW.DE', 'BMW AG', 'Consumer'],
    ['BAYN.DE', 'Bayer AG', 'Healthcare'],
    ['DTE.DE', 'Deutsche Telekom', 'Technology'],
    ['MBG.DE', 'Mercedes-Benz Group', 'Consumer'],
    ['MUV2.DE', 'Munich Re', 'Financials'],
    ['DB1.DE', 'Deutsche Börse', 'Financials'],
    ['RWE.DE', 'RWE AG', 'Utilities'],
    ['BAS.DE', 'BASF SE', 'Materials'],
    ['DHER.DE', 'Delivery Hero', 'Technology'],
    ['HEN3.DE', 'Henkel AG', 'Consumer'],
    ['MTX.DE', 'MTU Aero Engines', 'Industrials'],
    ['AIXA.DE', 'Aixtron SE', 'Technology'],
    ['BEI.DE', 'Beiersdorf AG', 'Consumer'],
    ['MRK.DE', 'Merck KGaA', 'Healthcare'],
    ['EOAN.DE', 'E.ON SE', 'Utilities'],
    ['DKCK.DE', 'Drk Schwesternschaft', 'Healthcare'],
    ['FME.DE', 'Fresenius Medical Care', 'Healthcare'],

    // ── FRANCE / EURONEXT ─────────────────────────────────────────
    ['MC.PA', 'LVMH Moët Hennessy', 'Consumer'],
    ['TTE.PA', 'TotalEnergies SE', 'Energy'],
    ['AIR.PA', 'Airbus SE', 'Industrials'],
    ['SAN.PA', 'Sanofi SA', 'Healthcare'],
    ['BNP.PA', 'BNP Paribas SA', 'Financials'],
    ['OR.PA', 'L\'Oréal SA', 'Consumer'],
    ['AI.PA', 'Air Liquide SA', 'Materials'],
    ['SG.PA', 'Société Générale', 'Financials'],
    ['VIE.PA', 'Veolia Environnement', 'Utilities'],
    ['KER.PA', 'Kering SA', 'Consumer'],
    ['ACA.PA', 'Crédit Agricole', 'Financials'],
    ['DG.PA', 'Vinci SA', 'Industrials'],
    ['RI.PA', 'Pernod Ricard SA', 'Consumer'],
    ['CS.PA', 'AXA SA', 'Financials'],
    ['CAP.PA', 'Capgemini SE', 'Technology'],

    // ── CANADA / TSX ──────────────────────────────────────────────
    ['RY.TO', 'Royal Bank of Canada', 'Financials'],
    ['TD.TO', 'TD Bank Group', 'Financials'],
    ['CNR.TO', 'Canadian National Railway', 'Industrials'],
    ['SHOP.TO', 'Shopify Inc.', 'Technology'],
    ['BCE.TO', 'BCE Inc.', 'Technology'],
    ['ENB.TO', 'Enbridge Inc.', 'Energy'],
    ['TRP.TO', 'TC Energy Corp.', 'Energy'],
    ['BNS.TO', 'Bank of Nova Scotia', 'Financials'],
    ['BMO.TO', 'Bank of Montreal', 'Financials'],
    ['MFC.TO', 'Manulife Financial', 'Financials'],
    ['SU.TO', 'Suncor Energy', 'Energy'],
    ['CNQ.TO', 'Canadian Natural Resources', 'Energy'],
    ['CP.TO', 'CP Kansas City Southern', 'Industrials'],
    ['CTC-A.TO', 'Canadian Tire Corp.', 'Consumer'],
    ['WPM.TO', 'Wheaton Precious Metals', 'Materials'],

    // ── AUSTRALIA / ASX ───────────────────────────────────────────
    ['BHP.AX', 'BHP Group Ltd.', 'Materials'],
    ['CBA.AX', 'Commonwealth Bank AU', 'Financials'],
    ['CSL.AX', 'CSL Ltd.', 'Healthcare'],
    ['WBC.AX', 'Westpac Banking Corp.', 'Financials'],
    ['RIO.AX', 'Rio Tinto Ltd.', 'Materials'],
    ['ANZ.AX', 'ANZ Banking Group', 'Financials'],
    ['NAB.AX', 'National Australia Bank', 'Financials'],
    ['MQG.AX', 'Macquarie Group', 'Financials'],
    ['WES.AX', 'Wesfarmers Ltd.', 'Consumer'],
    ['FMG.AX', 'Fortescue Metals', 'Materials'],
    ['WOW.AX', 'Woolworths Group', 'Consumer'],
    ['TCL.AX', 'Transurban Group', 'Industrials'],
    ['GMG.AX', 'Goodman Group', 'Real Estate'],
    ['TWE.AX', 'Treasury Wine Estates', 'Consumer'],
    ['NXT.AX', 'NextDC Ltd.', 'Technology'],

    // ── INDIA / NSE ───────────────────────────────────────────────
    ['RELIANCE.NS', 'Reliance Industries', 'Energy'],
    ['TCS.NS', 'Tata Consultancy Services', 'Technology'],
    ['INFY.NS', 'Infosys Ltd.', 'Technology'],
    ['HDFCBANK.NS', 'HDFC Bank Ltd.', 'Financials'],
    ['WIPRO.NS', 'Wipro Ltd.', 'Technology'],
    ['ICICIBANK.NS', 'ICICI Bank Ltd.', 'Financials'],
    ['LT.NS', 'Larsen & Toubro', 'Industrials'],
    ['HINDUNILVR.NS', 'Hindustan Unilever', 'Consumer'],
    ['ASIANPAINT.NS', 'Asian Paints', 'Materials'],
    ['ITC.NS', 'ITC Ltd.', 'Consumer'],
    ['BAJFINANCE.NS', 'Bajaj Finance', 'Financials'],
    ['MARUTI.NS', 'Maruti Suzuki India', 'Consumer'],
    ['SUNPHARMA.NS', 'Sun Pharmaceutical', 'Healthcare'],
    ['TATASTEEL.NS', 'Tata Steel Ltd.', 'Materials'],
    ['ONGC.NS', 'ONGC Ltd.', 'Energy'],

    // ── SWITZERLAND / SIX ─────────────────────────────────────────
    ['NESN.SW', 'Nestlé SA', 'Consumer'],
    ['NOVN.SW', 'Novartis AG', 'Healthcare'],
    ['ROG.SW', 'Roche Holding AG', 'Healthcare'],
    ['ABBN.SW', 'ABB Ltd.', 'Industrials'],
    ['CSGN.SW', 'Credit Suisse Group', 'Financials'],
    ['UBSG.SW', 'UBS Group AG', 'Financials'],
    ['ZURN.SW', 'Zurich Insurance Group', 'Financials'],
    ['CFR.SW', 'Compagnie Financière Richemont', 'Consumer'],
    ['GIVN.SW', 'Givaudan SA', 'Materials'],
    ['SREN.SW', 'Swiss Re AG', 'Financials'],

    // ── KOREA / KRX ───────────────────────────────────────────────
    ['005930.KS', 'Samsung Electronics', 'Technology'],
    ['000660.KS', 'SK Hynix Inc.', 'Technology'],
    ['005380.KS', 'Hyundai Motor Co.', 'Consumer'],
    ['035420.KS', 'Naver Corp.', 'Technology'],
    ['051910.KS', 'LG Chem Ltd.', 'Materials'],
    ['003550.KS', 'LG Corp.', 'Technology'],
    ['068270.KS', 'Celltrion Inc.', 'Healthcare'],
    ['030200.KS', 'KT Corp.', 'Technology'],
    ['009150.KS', 'Samsung Electro-Mechanics', 'Technology'],
    ['028260.KS', 'Samsung C&T', 'Industrials'],

    // ── NETHERLANDS / EURONEXT AMSTERDAM ────────────────────────
    ['ASML.AS', 'ASML Holding NV', 'Technology'],
    ['INGA.AS', 'ING Groep NV', 'Financials'],
    ['PHIA.AS', 'Philips NV', 'Healthcare'],
    ['ABN.AS', 'ABN AMRO Bank', 'Financials'],
    ['RAND.AS', 'Randstad NV', 'Industrials'],
    ['AKZA.AS', 'Akzo Nobel NV', 'Materials'],
    ['NN.AS', 'NN Group NV', 'Financials'],
    ['HEIA.AS', 'Heineken NV', 'Consumer'],

    // ── SPAIN / BME ───────────────────────────────────────────────
    ['SAN.MC', 'Banco Santander', 'Financials'],
    ['BBVA.MC', 'BBVA', 'Financials'],
    ['IBE.MC', 'Iberdrola SA', 'Utilities'],
    ['TEF.MC', 'Telefónica SA', 'Technology'],
    ['ITX.MC', 'Inditex', 'Consumer'],
    ['CLNX.MC', 'Cellnex Telecom', 'Technology'],

    // ── ITALY / MILAN ─────────────────────────────────────────────
    ['ENI.MI', 'Eni SpA', 'Energy'],
    ['ENEL.MI', 'Enel SpA', 'Utilities'],
    ['ISP.MI', 'Intesa Sanpaolo', 'Financials'],
    ['UCG.MI', 'UniCredit SpA', 'Financials'],
    ['FCA.MI', 'Stellantis NV', 'Consumer'],
    ['LDO.MI', 'Leonardo SpA', 'Industrials'],

    // ── BRAZIL / B3 ───────────────────────────────────────────────
    ['VALE3.SA', 'Vale SA', 'Materials'],
    ['PETR4.SA', 'Petrobras PN', 'Energy'],
    ['ITUB4.SA', 'Itaú Unibanco PN', 'Financials'],
    ['BBDC4.SA', 'Bradesco PN', 'Financials'],
    ['ABEV3.SA', 'Ambev SA', 'Consumer'],
    ['MGLU3.SA', 'Magazine Luiza', 'Consumer'],
    ['WEGE3.SA', 'WEG SA', 'Industrials'],
    ['RENT3.SA', 'Localiza Rent a Car', 'Consumer'],

    // ── SWEDEN / NASDAQ NORDIC ───────────────────────────────────
    ['ERIC-B.ST', 'Ericsson AB', 'Technology'],
    ['VOLV-B.ST', 'Volvo AB', 'Industrials'],
    ['ATCO-A.ST', 'Atlas Copco', 'Industrials'],
    ['SAND.ST', 'Sandvik AB', 'Materials'],
    ['HM-B.ST', 'H&M Group', 'Consumer'],
    ['ALFA.ST', 'Alfa Laval', 'Industrials'],
    ['SWED-A.ST', 'Swedbank AB', 'Financials'],
    ['SEB-A.ST', 'SEB AB', 'Financials'],

    // ── CHINA / SHANGHAI/HK ADR ──────────────────────────────────
    ['BIDU', 'Baidu Inc. ADR', 'Technology'],
    ['JD', 'JD.com ADR', 'Technology'],
    ['PDD', 'PDD Holdings ADR', 'Consumer'],
    ['BABA', 'Alibaba Group ADR', 'Technology'],
    ['NIO', 'NIO Inc. ADR', 'Consumer'],
    ['XPEV', 'XPeng Inc. ADR', 'Consumer'],
    ['LI', 'Li Auto Inc. ADR', 'Consumer'],

    // ── SINGAPORE / SGX ──────────────────────────────────────────
    ['D05.SI', 'DBS Group Holdings', 'Financials'],
    ['U11.SI', 'United Overseas Bank', 'Financials'],
    ['O39.SI', 'OCBC Bank', 'Financials'],
    ['Z74.SI', 'Singapore Telecom', 'Technology'],
    ['C6L.SI', 'Singapore Airlines', 'Consumer'],
    ['BN4.SI', 'Keppel Corp.', 'Industrials'],

    // ── HONG KONG - EXTRA ─────────────────────────────────────────
    ['9999.HK', 'NetEase Inc.', 'Technology'],
    ['3988.HK', 'Bank of China', 'Financials'],
    ['1398.HK', 'ICBC Ltd.', 'Financials'],
    ['0386.HK', 'China Petroleum (Sinopec)', 'Energy'],
    ['2628.HK', 'China Life Insurance', 'Financials'],
    ['1088.HK', 'China Shenhua Energy', 'Energy'],

    // ── TAIWAN / TWSE ────────────────────────────────────────────
    ['TSM', 'TSMC ADR (NYSE)', 'Technology'],
    ['2330.TW', 'TSMC (Taipei)', 'Technology'],
    ['2317.TW', 'Hon Hai Precision (Foxconn)', 'Technology'],
    ['2412.TW', 'Chunghwa Telecom', 'Technology'],
    ['2891.TW', 'CTBC Financial Holding', 'Financials'],

    // ── SAUDI ARABIA / TADAWUL ───────────────────────────────────
    ['2222.SR', 'Saudi Aramco', 'Energy'],
    ['1180.SR', 'Al Rajhi Bank', 'Financials'],
    ['2010.SR', 'SABIC', 'Materials'],
];

export default { SP500_COMPACT, GLOBAL_COMPACT };
